# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[17, 69],
       [57, 78],
       [18, 33],
       [69, 37],
       [36, 26],
       [28, 41],
       [65, 52],
       [39, 16],
       [92, 14],
       [33, 34]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

MinMaxScaler()

In [7]:
scaler_model.transform(data)

array([[0.        , 0.859375  ],
       [0.53333333, 1.        ],
       [0.01333333, 0.296875  ],
       [0.69333333, 0.359375  ],
       [0.25333333, 0.1875    ],
       [0.14666667, 0.421875  ],
       [0.64      , 0.59375   ],
       [0.29333333, 0.03125   ],
       [1.        , 0.        ],
       [0.21333333, 0.3125    ]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)

In [9]:
result

array([[0.        , 0.859375  ],
       [0.53333333, 1.        ],
       [0.01333333, 0.296875  ],
       [0.69333333, 0.359375  ],
       [0.25333333, 0.1875    ],
       [0.14666667, 0.421875  ],
       [0.64      , 0.59375   ],
       [0.29333333, 0.03125   ],
       [1.        , 0.        ],
       [0.21333333, 0.3125    ]])

In [10]:
import pandas as pd

In [11]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [12]:
data.head()

f1   f2  f3  label
0  51   16  34     62
1  75   64   2     90
2   6   84  73     37
3  86  100  86     85
4  84   86  94     42

In [13]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [16]:
X_train.shape

(35, 3)

In [17]:
X_test.shape

(15, 3)

In [18]:
y_train.shape

(35,)

In [19]:
y_test.shape

(15,)

## Great Job!