In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.3.1


## Tensors

In [4]:
hello = tf.constant('Hello')
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor: shape=(), dtype=string, numpy=b'HelloWorld'>

In [8]:
type(result)

tensorflow.python.framework.ops.EagerTensor

** Computations **

In [9]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [10]:
type(tensor_1)

tensorflow.python.framework.ops.EagerTensor

In [11]:
tensor_1 + tensor_2

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## Operations

In [12]:
const = tf.constant(10)

In [13]:
fill_mat = tf.fill((4,4),10)

In [14]:
myzeros = tf.zeros((4,4))

In [15]:
myones = tf.ones((4,4))

In [17]:
myrandn = tf.random.normal((4,4),mean=0,stddev=0.5)

In [18]:
myrandu = tf.random.uniform((4,4),minval=0,maxval=1)

In [19]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [21]:
for op in my_ops:
    print(op.numpy())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.16111973  0.8281926  -0.1441275   0.09168918]
 [ 0.18980676  0.33485344 -0.4635818  -0.23746538]
 [-0.19634414  0.1617646  -0.09598273  0.6581655 ]
 [ 0.14806652 -0.291271   -0.6891027  -0.18810338]]


[[0.5657157  0.0125742  0.9686818  0.80483735]
 [0.57208323 0.05784416 0.5762898  0.6101092 ]
 [0.22267294 0.7970723  0.517591   0.8033365 ]
 [0.7925612  0.5650054  0.04021728 0.8676393 ]]




## Matrix Multiplication

In [25]:
a = tf.constant([[1, 2], 
                 [3, 4]])
a.get_shape()

TensorShape([2, 2])

In [26]:
b = tf.constant([[10], [100]])
b.get_shape()

TensorShape([2, 1])

In [27]:
result = tf.matmul(a, b)

In [30]:
result.numpy()

array([[210],
       [430]])